kind: Service 
apiVersion: v1 
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 5000 
      targetPort: 5000
      name: portc
      protocol: UDP

    - port: 5001 
      targetPort: 5001
      name: portd
      protocol: UDP

