apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
{{- if eq .Values.name "upf"}}
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
  {{- end }}
{{- if eq .Values.name "amf"}}
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
  {{- end }}
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: virginiabrioso/{{ .Values.name }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
  {{- if eq .Values.name "webapp" }}
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/dev
  {{- end }}
  {{- if eq .Values.name "mongo" }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
  {{- end }}
        resources: {}
        securityContext:
  {{- if eq .Values.name "upf" }}
          capabilities:
            add:
            - NET_ADMIN
  {{- end }}
          privileged: true
      restartPolicy: Always
      serviceAccountName: ""
  {{- if eq .Values.name "mongo" }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
  {{- end }}
status: {}
