apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.name }}
  template:
    metadata:
{{- if eq .Values.name "upf"}}
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
  {{- end }}
{{- if eq .Values.name "amf"}}
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
  {{- end }}
      labels:
        io.kompose.network/cluster_net1: "true"
        io.kompose.service: {{ .Values.name }}
    spec:
      containers:
      - image: virginiabrioso/{{ .Values.name }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        resources: {}
        securityContext:
  {{- if eq .Values.name "upf" }}
          capabilities:
            add:
            - NET_ADMIN
  {{- end }}
          privileged: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
