{{- if eq .Values.name "webapp" -}}
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
{{- end }}
{{- if eq .Values.name "mongo" -}}
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
{{- end }}

