{{- if eq .Values.name "webapp" -}}
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
{{- end }}
